---
title: "Mood Disorder & Suicidality ~ Clustered Risk Group Modeling"
author: "Sam A. Sievertsen"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: true
---

```{r global, include = FALSE}

# Set global env variables
knitr::opts_chunk$set(warning = FALSE, message = NA, comment = "")

```

```{r environment, echo = FALSE, include = FALSE, warning = FALSE}

# Load necessary packages + environmental variables
library(knitr)
library(kableExtra)
library(dplyr)
library(tidyr)
library(easystats)
library(cluster)
library(clustMixType)
library(ggplot2)
library(plotly)
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
options(scipen = 999, digits = 8)

# Read in clustered risk variable + outcome data for analysis
bipolar_suicidality_risk_data <- read.csv("../../data/data_processed/bipolar_suicidality_risk_analysis_data.csv")

```

## Data Wrangling

```{r data wrangling, warning = FALSE}

## Data Wrangling for Analyses ## 

#1. Create a dataframe for primary analyses
#1.1 Retain only the columns of interest to the analyses
bipolar_suicidality_risk_primary_analysis_data <- bipolar_suicidality_risk_data %>% 
  dplyr::select(c(src_subject_id, sex, family_id, site_name, cluster, bipolar_I_dx, bipolar_II_dx, any_bipolar_dx, suicidal_thinking, suicide_attempt, nssi))

#1.2 Alter the names of clusters to better reflect their membership during modeling
bipolar_suicidality_risk_primary_analysis_data <- bipolar_suicidality_risk_primary_analysis_data %>%
  mutate(cluster = paste0("cluster_", cluster))

#1.3 Ensure columns of interest are the correct data type
#1.31 Set relevant columns to factor type
bipolar_suicidality_risk_primary_analysis_data <- bipolar_suicidality_risk_primary_analysis_data %>% 
  mutate(across(c("sex", "family_id", "site_name", "cluster", "bipolar_I_dx", "bipolar_II_dx", "any_bipolar_dx", "suicidal_thinking", "suicide_attempt", "nssi"), as.factor))

#1.32 Set reference level of the cluster variable
bipolar_suicidality_risk_primary_analysis_data$cluster <- relevel(bipolar_suicidality_risk_primary_analysis_data$cluster, ref = "cluster_3")

#2. Create a dataframe for secondary analyses
dimensional_psychopathology_risk_secondary_analysis_data <- bipolar_suicidality_risk_data %>% 
  dplyr::select(c())

#3. Create a dataframe for demographic data summarization
bipolar_suicidality_risk_demographic_data <- bipolar_suicidality_risk_data %>% 
  dplyr::select(c())

```

## Primary Analysis: Risk for Bipolar Disorder(s) & Suicidality

```{r}

# logistic regression for binary diagnostic outcomes 


```

### Plotting Primary Analysis Results

```{r}



```


## Secondary Analysis: Associations Between Risk Group + Dimensional Psychopathology

```{r}

# lmer -> ANCOVA -> post-hoc for continuous secondary outcomes


```

### Plotting Secondary Analysis Results

```{r}



```