---
title: "Mood Disorder & Suicidality Risk Variable Data Wrangling"
author: "Sam A. Sievertsen"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: true
---

```{r global, include = FALSE}

# Set global env variables
knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")

```

```{r environment, echo = FALSE, include = FALSE, warning = FALSE}

# Load necessary packages + environmental variables
library(knitr)
library(dplyr)
library(tidyr)
library(skimr)
options(scipen = 999, digits = 8)

# Load custom function to protect subject ID data
source("update_interview_age.R")

# Read in data containing variables directly implementable in risk group clustering
# cbcl data
cbcl_data <- read.csv("../../data/data_raw/mh_p_cbcl.csv")

# general behavior inventory data
gbi_data <- read.csv("../../data/data_raw/mh_p_gbi.csv")

# upps-p data
uppsp_data <- read.csv("../../data/data_raw/mh_y_upps.csv")

# sleep disturbance scale data
sleep_disturbance_data <- read.csv("../../data/data_raw/ph_p_sds.csv")

# family history data
family_hx_data <- read.csv("../../data/data_raw/mh_p_fhx.csv")

# childhood opportunity index data
coi_data <- read.csv("../../data/data_raw/led_l_coi.csv")

# parent KSADS-COMP background data
parent_ksads_bg_data <- read.csv("../../data/data_raw/mh_p_ksads_bg.csv")

# youth KSADS-COMP background data
youth_ksads_bg_data <- read.csv("../../data/data_raw/mh_y_ksads_bg.csv")

# neighborhood safety data
neighborhood_safety_data <- read.csv("../../data/data_raw/ce_p_nsc.csv")

# NIH-toolbox data
nihtb_data <- read.csv("../../data/data_raw/nc_y_nihtb.csv")

# Read in ACE Index Data
# KSADS-COMP PTSD Questions
ksads_ptsd_data <- read.csv("../../data/data_raw/mh_p_ksads_ptsd.csv")

# Parent reported demographics survey - family conflict subscale
parent_demo_conflict_data <- read.csv("../../data/data_raw/ce_p_fes.csv")

# Youth reported parental monitoring survey
youth_parental_monitoring_data <- read.csv("../../data/data_raw/ce_y_fes.csv")

# Family history data read in above

# Parent reported demographic data
parent_demographic_data <- read.csv("../../data/data_raw/abcd_p_demo.csv")

# Youth caregiver acceptance
youth_crpbi_data <- read.csv("../../data/data_raw/ce_y_crpbi.csv")

# Parental monitoring survey
parental_monitoring_data <- read.csv("../../data/data_raw/ce_y_pm.csv")

# Read in demographic/covariate data of interest
# Site name data
site_name_data <- read.csv("../../data/data_raw/mri_y_adm_info.csv")

# Family ID data
family_id_data <- read.csv("../../data/data_raw/abcd_y_lt.csv")

```

## Dataframe Merging

```{r data merging, warning = FALSE}

## Data Wrangling ##

#1. Merge the data
#1.1 Collapse the data frames containing risk variables of interest
risk_data_merged <- Reduce(
  function(x, y)
    merge(x, y,
      by = c("src_subject_id", "eventname"),
      all = TRUE),
  list(cbcl_data, gbi_data, uppsp_data, sleep_disturbance_data, family_hx_data, coi_data, parent_ksads_bg_data, youth_ksads_bg_data, neighborhood_safety_data, nihtb_data, ksads_ptsd_data, parent_demo_conflict_data, youth_parental_monitoring_data, parent_demographic_data, youth_crpbi_data, parental_monitoring_data))

#1.2 Verify the merge did not duplicate any columns and resulted in an expected 
#1.21 Check for duplicate columns
duplicate_columns <- grep("\\.x$|\\.y$", colnames(risk_data_merged), value = TRUE)
if (length(duplicate_columns) > 0) {
  message("Duplicate columns found: ", paste(duplicate_columns, collapse = ", "))
} else {
  message("No duplicate columns ending found.")
}

#1.22 Check the number of unique subjects to ensure no data was lost/erroneously created during merging
unique_count <- length(unique(risk_data_merged$src_subject_id))
if (unique_count >= 11800 && unique_count <= 12000) {
  message("The number of unique src_subject_id (", unique_count, ") with data present is within the possible range of sampled subjects.")
} else {
  message("The number of unique src_subject_id (", unique_count, ") is outside the acceptable range!")
}

#2. Clean the merged data 
#2.1 Retain only columns of interest
risk_data_merged_trimmed <- risk_data_merged %>% 
  dplyr::select(c(src_subject_id, eventname, cbcl_scr_dsm5_depress_t, cbcl_scr_dsm5_depress_nm, cbcl_scr_dsm5_anxdisord_t, cbcl_scr_dsm5_anxdisord_nm,	cbcl_scr_syn_attention_t, cbcl_scr_syn_attention_nm, cbcl_scr_syn_aggressive_t, cbcl_scr_syn_aggressive_nm, pgbi_p_ss_score, upps_y_ss_negative_urgency, upps_y_ss_negative_urgency_nm, upps_y_ss_positive_urgency, upps_y_ss_positive_urgency_nm, sds_p_ss_total, fam_history_6_yes_no, fam_history_q6a_depression, fam_history_q6d_depression, q6k_full_sib_young1_depression, q6k_full_sib_young2_depression, q6k_full_sib_young3_depression, q6k_full_sib_young4_depression, q6k_full_sib_young5_depression, q6l_full_sib_old1_depression, q6l_full_sib_old2_depression, q6l_full_sib_old3_depression, q6l_full_sib_old4_depression, q6l_full_sib_old5_depression, famhx_ss_momdad_ma_p, reshist_addr1_coi_z_coi_nat, kbi_p_c_bully, ksads_bully_raw_26, nsc_p_ss_mean_3_items, nsc_p_ss_mean_3_items_nm, nihtbx_list_uncorrected, nihtbx_flanker_uncorrected, nihtbx_pattern_uncorrected, ksads_ptsd_raw_762_p, ksads_ptsd_raw_763_p,  ksads_ptsd_raw_767_p, ksads_ptsd_raw_768_p, ksads_ptsd_raw_766_p, fam_enviro6_p, fam_enviro3_p, fes_youth_q6, fes_youth_q3, famhx_4_p, fam_history_13_yes_no, fam_history_5_yes_no, fam_history_6_yes_no, demo_prnt_marital_v2, fam_history_9_yes_no, crpbi_parent4_y, parent_monitor_q1_y, parent_monitor_q3_y))

#2.2 Filter the trimmed data to only contain rows at the baseline assessment timepoint
risk_data_merged_trimmed <- risk_data_merged_trimmed %>% 
  filter(eventname == "baseline_year_1_arm_1")

```

## Secondary Risk Variable Creation + Validation

```{r data wrangling, warning = FALSE}

## Data Wrangling ##

#1. Create relevant risk clustering variables
#1.1 Family (first-degree relative) history of depression
risk_data_merged_trimmed <- risk_data_merged_trimmed %>%
  mutate(
    family_history_depression = case_when(
      
      #1.11 Assign 1 if any first-degree relative has depression
      replace_na(fam_history_q6a_depression == 1, FALSE) |
        replace_na(fam_history_q6d_depression == 1, FALSE) |
        replace_na(q6k_full_sib_young1_depression == 1, FALSE) |
        replace_na(q6k_full_sib_young2_depression == 1, FALSE) |
        replace_na(q6k_full_sib_young3_depression == 1, FALSE) |
        replace_na(q6k_full_sib_young4_depression == 1, FALSE) |
        replace_na(q6k_full_sib_young5_depression == 1, FALSE) |
        replace_na(q6l_full_sib_old1_depression == 1, FALSE) |
        replace_na(q6l_full_sib_old2_depression == 1, FALSE) |
        replace_na(q6l_full_sib_old3_depression == 1, FALSE) |
        replace_na(q6l_full_sib_old4_depression == 1, FALSE) |
        replace_na(q6l_full_sib_old5_depression == 1, FALSE) ~ 1,
      
      #1.12 Assign 0 if "fam_history_6_yes_no" is 1 but no first-degree relative has depression
      fam_history_6_yes_no == 1 ~ 0,
      
      #1.13 Assign 0 if "fam_history_6_yes_no" is 0
      fam_history_6_yes_no == 0 ~ 0,
      
      #1.14 Otherwise, assign NA
      TRUE ~ NA_real_))

#1.2 Sum ACE Score Index
risk_data_merged_trimmed <- risk_data_merged_trimmed %>%
  mutate(
    
    #1.211 Calculate each ACE component
    ACE_1 = if_else(fam_history_9_yes_no == 1, 1, 0, missing = 0),
    ACE_2 = if_else(crpbi_parent4_y %in% c(1, 2), 1, 0, missing = 0),
    ACE_3 = if_else(fam_history_13_yes_no == 1 | fam_history_6_yes_no == 1, 1, 0, missing = 0),
    ACE_4 = if_else(famhx_4_p == 1 | fam_history_5_yes_no == 1, 1, 0, missing = 0),
    ACE_5 = if_else(ksads_ptsd_raw_766_p == 1 | fes_youth_q6 == 1 | fes_youth_q3 == 1, 1, 0, missing = 0),
    ACE_6 = if_else(demo_prnt_marital_v2 %in% c(2, 3, 4), 1, 0, missing = 0),
    ACE_7 = if_else(ksads_ptsd_raw_762_p == 1 | ksads_ptsd_raw_763_p == 1, 1, 0, missing = 0),
    ACE_8 = if_else(parent_monitor_q1_y %in% c(1, 2) | parent_monitor_q3_y %in% c(1, 2), 1, 0, missing = 0),
    ACE_9 = if_else(ksads_ptsd_raw_767_p == 1 | ksads_ptsd_raw_768_p == 1, 1, 0, missing = 0),
    
    #1.212 Sum the ACE components for each participant
    ACE_index_sum_score = rowSums(across(starts_with("ACE_") & 
               !matches("ACE_index_sum_score|ACE_index_sum_score_n_missing")), na.rm = TRUE),
    
    #1.22 Count the number of missing values for the ACE components
    ACE_index_sum_score_n_missing = rowSums(
      across(c(
        fam_history_9_yes_no, crpbi_parent4_y, fam_history_13_yes_no, fam_history_6_yes_no, 
        famhx_4_p, fam_history_5_yes_no, ksads_ptsd_raw_766_p, fes_youth_q6, fes_youth_q3,
        demo_prnt_marital_v2, ksads_ptsd_raw_762_p, ksads_ptsd_raw_763_p, 
        parent_monitor_q1_y, parent_monitor_q3_y, ksads_ptsd_raw_767_p, ksads_ptsd_raw_768_p
      ), ~ . %in% c(NA, "", 999, 7, 777))))

#1.3 Bullying
risk_data_merged_trimmed <- risk_data_merged_trimmed %>%
  mutate(bullying = case_when(
    kbi_p_c_bully == 1 | ksads_bully_raw_26 == 1 ~ 1, 
    is.na(kbi_p_c_bully) & is.na(ksads_bully_raw_26) ~ NA_real_,
    kbi_p_c_bully == "" & ksads_bully_raw_26 == "" ~ NA_real_,
    TRUE ~ 0))


#2. Validate the family history of depression, ACE index, and bullying variables
#2.1 Family history of depression
#2.11 Generate a frequency table to list generated values
table(risk_data_merged_trimmed$family_history_depression, useNA = "ifany")

#2.121 Define the specific columns used for family history of depression
family_history_columns <- c(
  "fam_history_6_yes_no",
  "fam_history_q6a_depression",
  "fam_history_q6d_depression",
  "q6k_full_sib_young1_depression",
  "q6k_full_sib_young2_depression",
  "q6k_full_sib_young3_depression",
  "q6k_full_sib_young4_depression",
  "q6k_full_sib_young5_depression",
  "q6l_full_sib_old1_depression",
  "q6l_full_sib_old2_depression",
  "q6l_full_sib_old3_depression",
  "q6l_full_sib_old4_depression",
  "q6l_full_sib_old5_depression")

#2.122 Verify edge cases: family history variable inconsistencies
risk_data_merged_trimmed %>%
  filter(fam_history_6_yes_no == 1 & family_history_depression == 0) %>%
  dplyr::select(all_of(family_history_columns), family_history_depression) %>% 
  head()

#2.123 Verify cases where family history of depression is present
risk_data_merged_trimmed %>%
  filter(family_history_depression == 1) %>%
  dplyr::select(all_of(family_history_columns), family_history_depression) %>% 
  head()

#2.2 Sum ACE index
#2.21 Generate a summary of the ACE index
summary(risk_data_merged_trimmed$ACE_index_sum_score)

# 2.22 Verify sum computation for random samples (exclude ACE_index_sum_score and ACE_index_sum_score_n_missing)
risk_data_merged_trimmed %>%
  sample_n(5) %>%
  mutate(
    calculated_sum = rowSums(
      across(starts_with("ACE_") & 
               !matches("ACE_index_sum_score|ACE_index_sum_score_n_missing")),
      na.rm = TRUE)) %>%
  dplyr::select(ACE_index_sum_score, calculated_sum, 
         starts_with("ACE_") & 
         !matches("ACE_index_sum_score|ACE_index_sum_score_n_missing"))

#2.23 Check rows with missing ACE components (exclude derived columns in selection)
risk_data_merged_trimmed %>%
  filter(ACE_index_sum_score_n_missing > 0) %>%
  dplyr::select(
    ACE_index_sum_score,
    ACE_index_sum_score_n_missing,
    starts_with("ACE_") & !matches("ACE_index_sum_score|ACE_index_sum_score_n_missing")) %>% 
  head()

#2.3 Bullying
#2.31 Generate a frequency table of identified values
table(risk_data_merged_trimmed$bullying, useNA = "ifany")

#2.32 Validate cases where bullying is 1
risk_data_merged_trimmed %>%
  filter(bullying == 1) %>%
  select(kbi_p_c_bully, ksads_bully_raw_26, bullying) %>% 
  head()

#2.33 Validate cases where bullying is NA
risk_data_merged_trimmed %>%
  filter(is.na(bullying)) %>%
  select(kbi_p_c_bully, ksads_bully_raw_26, bullying) %>% 
  head()

#3. Merge in demographic/covariate data of interest
#3.1 Clean and merge all demographic/covariate data of interest
#3.111 Create the imaging site name variable 
site_name_data$imaging_site_name <- substr(site_name_data$mri_info_visitid, 1, 4)

#3.112 Retain only the site name variable at the baseline timepoint
site_name_data <- site_name_data %>% 
  filter(eventname == "baseline_year_1_arm_1") %>% 
  dplyr::select(c(src_subject_id, imaging_site_name))

#3.12 Obtain the biological sex and race-ethnicity variables from the parent demographic data
#3.121 Subset the variables of interest at the baseline timepoint
sex_ethnicity_data <- parent_demographic_data %>% 
  dplyr::select(c(src_subject_id, eventname, demo_sex_v2, race_ethnicity)) %>% 
  filter(eventname == "baseline_year_1_arm_1")

#3.122 Alter the biological sex name + values
sex_ethnicity_data$sex <- sex_ethnicity_data$demo_sex_v2
sex_ethnicity_data$sex[sex_ethnicity_data$sex == 1] <- "M"
sex_ethnicity_data$sex[sex_ethnicity_data$sex == 2] <- "F"
sex_ethnicity_data$sex[sex_ethnicity_data$sex == 3] <- "Other"

#3.123 Alter the race-ethnicity coded values
sex_ethnicity_data$race_ethnicity[sex_ethnicity_data$race_ethnicity == 1] <- "White"
sex_ethnicity_data$race_ethnicity[sex_ethnicity_data$race_ethnicity == 2] <- "Black"
sex_ethnicity_data$race_ethnicity[sex_ethnicity_data$race_ethnicity == 3] <- "Hispanic"
sex_ethnicity_data$race_ethnicity[sex_ethnicity_data$race_ethnicity == 4] <- "Asian"
sex_ethnicity_data$race_ethnicity[sex_ethnicity_data$race_ethnicity == 5] <- "Other"
sex_ethnicity_data$race_ethnicity[sex_ethnicity_data$race_ethnicity == ""] <- "Unsure"
sex_ethnicity_data$race_ethnicity[is.na(sex_ethnicity_data$race_ethnicity)] <- "Unsure"

#3.124 Retain only columns of interest
sex_ethnicity_data <- sex_ethnicity_data %>% 
  dplyr::select(c(src_subject_id, sex, race_ethnicity))

#3.13 Obtain the family id, age, and age in years variables 
#3.131 Subset the variables of interest at the baseline assessment timepoint
family_id_site_age_data <- family_id_data %>% 
  dplyr::select(c(src_subject_id, eventname, site_id_l, rel_family_id, interview_age)) %>% 
  filter(eventname == "baseline_year_1_arm_1")

#3.132 Change the name of the family id column
colnames(family_id_site_age_data)[colnames(family_id_site_age_data) == "rel_family_id"] <- "family_id"

#3.133 Change the name of the site id column
colnames(family_id_site_age_data)[colnames(family_id_site_age_data) == "site_id_l"] <- "site_name"

```

... Manually adding in interview_age values that were excluded from the data ...

```{r add in age values, echo = FALSE, warning = FALSE}

## Manually Add in Age Values Where Missing in the Data ## 

#1. Apply the function to the family ID / age dataframe
family_id_site_age_data <- update_interview_age(family_id_site_age_data)

```


``` {r data wrangling cont, warning = FALSE}

## Data Wrangling Continued ## 

#3.133 Compute the age in years column
family_id_site_age_data$age_in_years <- ((family_id_site_age_data$interview_age) / 12)

#3.134 Retain only columns of interest
family_id_site_age_data <- family_id_site_age_data %>% 
  dplyr::select(c(src_subject_id, family_id, site_name, interview_age, age_in_years))

#3.2 Merge all demographic/covariate data together
demographic_covariate_data <- Reduce(
  function(x, y)
    merge(x, y,
      by = "src_subject_id",
      all = TRUE),
  list(sex_ethnicity_data, family_id_site_age_data))

#3.3 Merge all demographic/covariate data with the risk variable data
risk_demographic_data_merged_trimmed <- left_join(risk_data_merged_trimmed, demographic_covariate_data)

```

## Data Cleaning + Summation

```{r final dataframe cleaning, warning = FALSE}

## Data Cleaning ##

#1. Create a dataframe containing only ordered variables of interest to risk group clustering
risk_variable_data <- risk_demographic_data_merged_trimmed %>% 
  dplyr::select(c(src_subject_id, eventname, family_id, site_name, sex, interview_age, age_in_years, race_ethnicity, cbcl_scr_dsm5_depress_t, cbcl_scr_dsm5_depress_nm, cbcl_scr_dsm5_anxdisord_t, cbcl_scr_dsm5_anxdisord_nm, cbcl_scr_syn_attention_t, cbcl_scr_syn_attention_nm, cbcl_scr_syn_aggressive_t, cbcl_scr_syn_aggressive_nm, pgbi_p_ss_score, upps_y_ss_negative_urgency, upps_y_ss_negative_urgency_nm, upps_y_ss_positive_urgency, upps_y_ss_positive_urgency_nm, sds_p_ss_total, family_history_depression, famhx_ss_momdad_ma_p, reshist_addr1_coi_z_coi_nat, nsc_p_ss_mean_3_items, nsc_p_ss_mean_3_items_nm, bullying, nihtbx_list_uncorrected, nihtbx_flanker_uncorrected, nihtbx_pattern_uncorrected, ACE_index_sum_score, ACE_index_sum_score_n_missing))

#2. Retain only subjects with complete data in columns of interest
#2.1 Transform any scores that were created with missing questions/data into NA values
#2.11 CBCL DSM-Oriented Depression Problems
risk_variable_data <- risk_variable_data %>%
  mutate(cbcl_scr_dsm5_depress_t = ifelse(cbcl_scr_dsm5_depress_nm > 0, NA, cbcl_scr_dsm5_depress_t))

#2.12 CBCL DSM-Oriented Anxiety Problems
risk_variable_data <- risk_variable_data %>%
  mutate(cbcl_scr_dsm5_anxdisord_t = ifelse(cbcl_scr_dsm5_anxdisord_nm > 0, NA, cbcl_scr_dsm5_anxdisord_t))

#2.13 CBCL Attention Problems
risk_variable_data <- risk_variable_data %>%
  mutate(cbcl_scr_syn_attention_t = ifelse(cbcl_scr_syn_attention_nm > 0, NA, cbcl_scr_syn_attention_t))

#2.14 CBCL Aggression Problems
risk_variable_data <- risk_variable_data %>%
  mutate(cbcl_scr_syn_aggressive_t = ifelse(cbcl_scr_syn_aggressive_nm > 0, NA, cbcl_scr_syn_aggressive_t))

#2.15 UPPS-P Negative Urgency 
risk_variable_data <- risk_variable_data %>%
  mutate(upps_y_ss_negative_urgency = ifelse(upps_y_ss_negative_urgency_nm > 0, NA, upps_y_ss_negative_urgency))

#2.16 UPPS-P Positive Urgency
risk_variable_data <- risk_variable_data %>%
  mutate(upps_y_ss_positive_urgency = ifelse(upps_y_ss_positive_urgency_nm > 0, NA, upps_y_ss_positive_urgency))

#2.17 Neighborhood Safety Index
risk_variable_data <- risk_variable_data %>%
  mutate(nsc_p_ss_mean_3_items = ifelse(nsc_p_ss_mean_3_items_nm > 0, NA, nsc_p_ss_mean_3_items))

#2.18 ACE Index Sum Score
risk_variable_data <- risk_variable_data %>%
  mutate(ACE_index_sum_score = ifelse(ACE_index_sum_score_n_missing > 0, NA, ACE_index_sum_score))

#2.2 Further subset the data to contain only columns of interest to clustering
risk_variable_data <- risk_variable_data %>% 
  dplyr::select(c(src_subject_id, eventname, family_id, site_name, sex, interview_age, age_in_years, race_ethnicity, cbcl_scr_dsm5_depress_t, cbcl_scr_dsm5_anxdisord_t, cbcl_scr_syn_attention_t, cbcl_scr_syn_aggressive_t, pgbi_p_ss_score, upps_y_ss_negative_urgency, upps_y_ss_positive_urgency, sds_p_ss_total, family_history_depression, famhx_ss_momdad_ma_p, reshist_addr1_coi_z_coi_nat, nsc_p_ss_mean_3_items, bullying, nihtbx_list_uncorrected, nihtbx_flanker_uncorrected, nihtbx_pattern_uncorrected, ACE_index_sum_score))

#2.3 Remove rows with missing data
risk_variable_data_clean <- risk_variable_data %>% 
  filter(complete.cases(.) & !if_any(everything(), ~ . == ""))

#3. Summarize final dataset
skimr::skim(risk_variable_data_clean)

```

## Writing Output to Processed Data Directory

```{r output, warning = FALSE}

## Output ##

#1. Write the cleaned risk variable data as a csv file to be used in clustering
write.csv(risk_variable_data_clean, "../../data/data_processed/risk_variable_data.csv", row.names = FALSE)

```

